language: go
go:
  - 1.3
before_install:
  - cd ..
  - git clone https://github.com/spf13/hugo.git
  - cd hugo
  - go get
  - cd ../website
install:
  - sudo apt-get install nodejs npm
  - npm install -qg bower grunt-cli
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "${GIT_NAME}"
script:
  - cd themes
  - git clone https://github.com/wet-boew/wet-boew-hugo.git wxt
  - cd wxt && bower install && cd ../..
  - ./deploy.sh "Initial commit" > /dev/null 2>&1
